language: cpp
dist: bionic

matrix:
    include:
        # Ubuntu Linux 18.04 gcc-7.1
        - os: linux
          compiler: gcc
          before_install:
              - export CXX="g++-7" CC="gcc-7"
              - export BUILD="make"

        # Ubuntu Linux 18.04 clang-7.0
        - os: linux
          compiler: clang
          packages:
              - clang
              - libc++-dev
              - libc++abi-dev
          before_install:
              - export CXX="clang++" CC="clang"
              - export BUILD="make"

        # Apple OSX LLVM version 10.0.0 (clang-1000.11.45.5)
        - os: osx
          osx_image: xcode10.2
          compiler: clang
          before_install:
              - export BUILD="make" 

        # OSX gcc-7
        - os: osx
          osx_image: xcode10.2
          compiler: gcc
          before_install:
              - rm -rf /usr/local/include/c++
              - brew update
              - brew install gcc@7
              - export CXX="g++-7" CC="gcc-7"
              - export BUILD="make"
              - sudo softwareupdate -i "Command Line Tools (macOS Mojave version 10.14) for Xcode-10.2"

notifications:
  email: false

script:
  - $CXX --version
  
  # Build the examples
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug && $BUILD

  # Run the unit tests
  - ./unit_tests/unit_tests
