version: 1.0.{build}

image: Visual Studio 2019

platform: x64

environment: 
  matrix:
    - compiler: msvc2019
    - compiler: msys2

build_script:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\.appveyor\appveyor_build.bat'
        
test_script:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\.appveyor\appveyor_test.bat'
